fix bug in determining serial console device name (bsc#1198043)
openSUSE/hwinfo pull request #112
Opened 2022-04-12 11:01 UTC by wfeldt

2022-04-12 12:49 UTC, shundhammer approved these changes
LGTM

2022-04-13 05:00 UTC, jirislaby requested changes
Actually, why not use `ttyname(3)`?

^^^ because the code opens `/dev/console`, I see now.

2022-04-13 05:00 UTC, jirislaby commented on src/hd/kbd.c
> +      }
Ditto with `sizeof`.

2022-04-13 07:17 UTC, wfeldt commented on src/hd/kbd.c
> +      dev_name = realpath(dev_link, NULL);
Nor `dev_link`. Thanks for spotting.

2022-04-13 07:17 UTC, wfeldt commented on src/hd/kbd.c
> +        !strncmp(dev_name, "/dev/", sizeof "/dev/" - 1)
I know, but I still like the sizeof variant.

2022-04-13 07:20 UTC, merged